
### Handling NULL values

In [1]:
import pandas as pd

In [2]:
# when the name of column is different in both the dataframes
df1 = pd.DataFrame({
    'id1': [1,2,3,4],
    'name': ['Dhruv', 'Amit', 'Educosys', 'Youtube']
})

df2 = pd.DataFrame({
    'id2': [3,4,5,6],
    'course': ['GenAI', 'CPP', 'HLD', 'LLD']
})

inner_result = pd.concat([df1, df2], axis = 0)
inner_result

   id1      name  id2 course
0  1.0     Dhruv  NaN    NaN
1  2.0      Amit  NaN    NaN
2  3.0  Educosys  NaN    NaN
3  4.0   Youtube  NaN    NaN
0  NaN       NaN  3.0  GenAI
1  NaN       NaN  4.0    CPP
2  NaN       NaN  5.0    HLD
3  NaN       NaN  6.0    LLD

In [3]:
inner_result.isna()

     id1   name    id2  course
0  False  False   True    True
1  False  False   True    True
2  False  False   True    True
3  False  False   True    True
0   True   True  False   False
1   True   True  False   False
2   True   True  False   False
3   True   True  False   False

In [4]:
inner_result.notna()

     id1   name    id2  course
0   True   True  False   False
1   True   True  False   False
2   True   True  False   False
3   True   True  False   False
0  False  False   True    True
1  False  False   True    True
2  False  False   True    True
3  False  False   True    True

In [6]:
inner_result.isna().sum()
inner_result.notna().sum()

id1       4
name      4
id2       4
course    4
dtype: int64