In [1]:
import pandas as pd

In [2]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [3]:
# Dataframe
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A', 'B', 'C'], index =['row1', 'row2', 'row3'])
print(df)

      A  B  C
row1  1  2  3
row2  4  5  6
row3  7  8  9

In [ ]:
#Reading data from a csv file
obesity_data = pd.read_csv('./obesity_pandas_practice.csv')
obesity_data.head() #to display the first 5 rows of the dataframe
obesity_data.tail() #to display the last 5 rows of the dataframe, write obesity_data.tail(10) to display the last 10 rows of the dataframe
obesity_data.info() #to display the summary of the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          120 non-null    str
 1   Age             119 non-null    float64
 2   Height          119 non-null    float64
 3   Weight          119 non-null    float64
 4   family_history  119 non-null    str
 5   FAVC            120 non-null    str
 6   FCVC            120 non-null    float64
 7   NCP             120 non-null    float64
 8   CAEC            119 non-null    str
 9   SMOKE           120 non-null    str
 10  CH2O            119 non-null    float64
 11  SCC             120 non-null    str
 12  FAF             120 non-null    float64
 13  TUE             120 non-null    float64
 14  CALC            119 non-null    str
 15  MTRANS          119 non-null    str
 16  Obesity         120 non-null    str
dtypes: float64(8), str(9)
memory usage: 16.1 KB

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
24,Male,33.0,1.68,68.7,yes,yes,2.1,3.9,Always,no,1.2,no,1.0,1.1,no,Automobile,Normal_Weight
107,Male,22.0,1.80,60.9,no,no,2.1,2.8,Sometimes,no,1.7,yes,1.8,0.7,Sometimes,Motorbike,Normal_Weight
66,Female,38.0,1.56,45.1,no,yes,2.0,1.7,no,no,1.9,no,2.9,0.9,Frequently,Automobile,Normal_Weight
30,Male,41.0,1.74,95.4,no,yes,2.6,3.3,Frequently,no,3.0,no,1.7,1.2,Always,Motorbike,Obesity_Type_I
5,Female,56.0,1.56,62.8,yes,no,1.6,1.2,Frequently,no,3.4,no,0.3,0.0,Sometimes,Automobile,Overweight_Level_I

In [17]:
#To generate random data from sample
obesity_data.sample()
obesity_data.sample(5) #to display 5 random rows of the dataframe, write obesity_data.sample(10) to display 10 random rows of the dataframe

#to fix the state of data to generate same random data every time, we can use the random_state parameter
obesity_data.sample(5, random_state = 1) #to display 5 random rows of the dataframe, write obesity_data.sample(10, random_state = 1) to display 10 random rows of the dataframe

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
95,Male,53.0,1.70,69.8,yes,yes,2.1,3.3,Always,yes,1.7,no,1.8,0.2,Sometimes,Walking,Normal_Weight
54,Female,46.0,1.74,55.5,no,no,2.6,4.0,Frequently,no,1.3,no,1.0,0.2,Sometimes,Walking,Insufficient_Weight
59,Female,58.0,1.63,69.7,yes,yes,2.1,1.1,Frequently,no,3.0,no,1.4,0.0,Sometimes,Public_Transportation,Overweight_Level_I
117,Male,56.0,1.57,93.7,no,no,2.9,2.8,no,yes,3.5,no,1.8,0.3,Always,Automobile,Obesity_Type_II
77,Female,49.0,1.53,48.5,no,yes,2.8,2.3,no,no,2.8,no,2.3,1.2,Frequently,Motorbike,Normal_Weight

In [22]:
#converting columns to a list
columns_list = obesity_data.columns.tolist() #to convert the columns of the dataframe to a list
print(columns_list) #to display the list of columns of the dataframe
print(list(obesity_data.index)) #to display the list of indices of the dataframe

['Gender', 'Age', 'Height', 'Weight', 'family_history', 'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'Obesity']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]

In [24]:
#properties of dataset
obesity_data.shape #to display the shape of the dataframe
obesity_data.size #to display the size of the dataframe

2040

In [25]:
obesity_data.describe() #to display the statistical summary of the dataframe

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,119.000000,119.000000,119.000000,120.000000,120.000000,119.000000,120.000000,120.000000
mean,40.327731,1.689664,71.258824,2.005833,2.635833,2.269748,1.584167,0.930000
std,11.517201,0.119135,16.420948,0.532837,0.829275,0.750768,0.874666,0.527655
min,18.000000,1.500000,43.100000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,30.000000,1.580000,59.400000,1.675000,2.100000,1.700000,0.875000,0.500000
50%,41.000000,1.690000,69.500000,2.050000,2.700000,2.300000,1.700000,0.900000
75%,50.500000,1.795000,82.550000,2.400000,3.300000,2.800000,2.300000,1.300000
max,60.000000,1.890000,125.300000,3.000000,4.000000,3.500000,3.000000,2.000000

In [26]:
df.columns #to display the columns of the dataframe

Index(['A', 'B', 'C'], dtype='str')

In [27]:
df.shape

(3, 3)

In [ ]:
df.index #to display the index of the dataframe

TypeError: 'Index' object is not callable

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, row1 to row3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [32]:
df.info

<bound method DataFrame.info of       A  B  C
row1  1  2  3
row2  4  5  6
row3  7  8  9>