### Merge, joins and concatenate

In [2]:
import pandas as pd

In [3]:
ob_data = pd.read_csv('./obesity_pandas_practice.csv')

In [6]:
df1 = pd.DataFrame({
    'id' : [1,2,3,4],
    'name': ['Dhruv', 'Amit', 'Educosys', 'Youtube']
})

df2 = pd.DataFrame({
    'id': [3,4,5,6],
    'course': ['GenAI', 'CPP', 'HLD', 'LLD']
})

In [ ]:
inner_result = pd.merge(df1, df2, how = 'inner', on = 'id') # inner join is like intersection
inner_result

   id      name course
0   3  Educosys  GenAI
1   4   Youtube    CPP

In [ ]:
outer_result = pd.merge(df1, df2, how = 'outer', on = 'id') # outer join is like union
outer_result

   id      name course
0   1     Dhruv    NaN
1   2      Amit    NaN
2   3  Educosys  GenAI
3   4   Youtube    CPP
4   5       NaN    HLD
5   6       NaN    LLD

In [10]:
# when the name of column is different in both the dataframes
df3 = pd.DataFrame({
    'id1': [1,2,3,4],
    'name': ['Dhruv', 'Amit', 'Educosys', 'Youtube']
})

df4 = pd.DataFrame({
    'id2': [3,4,5,6],
    'course': ['GenAI', 'CPP', 'HLD', 'LLD']
})

inner_result = pd.merge(df3, df4, how = 'inner', left_on = 'id1', right_on = 'id2')
inner_result

   id1      name  id2 course
0    3  Educosys    3  GenAI
1    4   Youtube    4    CPP